//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Core.Objects.DataClasses;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("dbSIMailerModel", "FK_tblMails_tblMailCategory", "tblMailCategory", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.One, typeof(SIMailer.Models.tblMailCategory), "tblMail", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SIMailer.Models.tblMail), true)]
[assembly: EdmRelationshipAttribute("dbSIMailerModel", "FK_tblSendTo_tblMails", "tblMail", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.One, typeof(SIMailer.Models.tblMail), "tblSendTo", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SIMailer.Models.tblSendTo), true)]
[assembly: EdmRelationshipAttribute("dbSIMailerModel", "FK_tblPerson_tblPersonType", "tblPersonType", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.One, typeof(SIMailer.Models.tblPersonType), "tblPerson", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SIMailer.Models.tblPerson), true)]
[assembly: EdmRelationshipAttribute("dbSIMailerModel", "FK_tblSendTo_tblPerson", "tblPerson", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.One, typeof(SIMailer.Models.tblPerson), "tblSendTo", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SIMailer.Models.tblSendTo), true)]

#endregion

namespace SIMailer.Models
{
    #region Contexts

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class dbSIMailerEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new dbSIMailerEntities object using the connection string found in the 'dbSIMailerEntities' section of the application configuration file.
        /// </summary>
        public dbSIMailerEntities() : base("name=dbSIMailerEntities", "dbSIMailerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dbSIMailerEntities object.
        /// </summary>
        public dbSIMailerEntities(string connectionString) : base(connectionString, "dbSIMailerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dbSIMailerEntities object.
        /// </summary>
        public dbSIMailerEntities(EntityConnection connection) : base(connection, "dbSIMailerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblMailCategory> tblMailCategories
        {
            get
            {
                if ((_tblMailCategories == null))
                {
                    _tblMailCategories = base.CreateObjectSet<tblMailCategory>("tblMailCategories");
                }
                return _tblMailCategories;
            }
        }
        private ObjectSet<tblMailCategory> _tblMailCategories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblMail> tblMails
        {
            get
            {
                if ((_tblMails == null))
                {
                    _tblMails = base.CreateObjectSet<tblMail>("tblMails");
                }
                return _tblMails;
            }
        }
        private ObjectSet<tblMail> _tblMails;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblPerson> tblPersons
        {
            get
            {
                if ((_tblPersons == null))
                {
                    _tblPersons = base.CreateObjectSet<tblPerson>("tblPersons");
                }
                return _tblPersons;
            }
        }
        private ObjectSet<tblPerson> _tblPersons;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblPersonType> tblPersonTypes
        {
            get
            {
                if ((_tblPersonTypes == null))
                {
                    _tblPersonTypes = base.CreateObjectSet<tblPersonType>("tblPersonTypes");
                }
                return _tblPersonTypes;
            }
        }
        private ObjectSet<tblPersonType> _tblPersonTypes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblSendTo> tblSendTo
        {
            get
            {
                if ((_tblSendToes == null))
                {
                    _tblSendToes = base.CreateObjectSet<tblSendTo>("tblSendToes");
                }
                return _tblSendToes;
            }
        }
        private ObjectSet<tblSendTo> _tblSendToes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblAdmin> tblAdmins
        {
            get
            {
                if ((_tblAdmins == null))
                {
                    _tblAdmins = base.CreateObjectSet<tblAdmin>("tblAdmins");
                }
                return _tblAdmins;
            }
        }
        private ObjectSet<tblAdmin> _tblAdmins;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblMailCategories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblMailCategories(tblMailCategory tblMailCategory)
        {
            base.AddObject("tblMailCategories", tblMailCategory);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblMails EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblMails(tblMail tblMail)
        {
            base.AddObject("tblMails", tblMail);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblPersons EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblPersons(tblPerson tblPerson)
        {
            base.AddObject("tblPersons", tblPerson);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblPersonTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblPersonTypes(tblPersonType tblPersonType)
        {
            base.AddObject("tblPersonTypes", tblPersonType);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblSendToes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblSendToes(tblSendTo tblSendTo)
        {
            base.AddObject("tblSendToes", tblSendTo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblAdmins EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblAdmins(tblAdmin tblAdmin)
        {
            base.AddObject("tblAdmins", tblAdmin);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbSIMailerModel", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value, "principal_id");
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value, "diagram_id");
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value, "version");
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true, "definition");
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbSIMailerModel", Name="tblAdmin")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblAdmin : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblAdmin object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="emailId">Initial value of the EmailId property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        public static tblAdmin CreatetblAdmin(global::System.Int32 id, global::System.String emailId, global::System.String password)
        {
            tblAdmin tblAdmin = new tblAdmin();
            tblAdmin.Id = id;
            tblAdmin.EmailId = emailId;
            tblAdmin.Password = password;
            return tblAdmin;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EmailId
        {
            get
            {
                return _EmailId;
            }
            set
            {
                OnEmailIdChanging(value);
                ReportPropertyChanging("EmailId");
                _EmailId = StructuralObject.SetValidValue(value, false, "EmailId");
                ReportPropertyChanged("EmailId");
                OnEmailIdChanged();
            }
        }
        private global::System.String _EmailId;
        partial void OnEmailIdChanging(global::System.String value);
        partial void OnEmailIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false, "Password");
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbSIMailerModel", Name="tblMail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblMail : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblMail object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="categoryId">Initial value of the CategoryId property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="subject">Initial value of the Subject property.</param>
        /// <param name="body">Initial value of the Body property.</param>
        /// <param name="adminId">Initial value of the AdminId property.</param>
        public static tblMail CreatetblMail(global::System.Int32 id, global::System.Int32 categoryId, global::System.String title, global::System.String subject, global::System.String body, global::System.Int32 adminId)
        {
            tblMail tblMail = new tblMail();
            tblMail.Id = id;
            tblMail.CategoryId = categoryId;
            tblMail.Title = title;
            tblMail.Subject = subject;
            tblMail.Body = body;
            tblMail.AdminId = adminId;
            return tblMail;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CategoryId
        {
            get
            {
                return _CategoryId;
            }
            set
            {
                OnCategoryIdChanging(value);
                ReportPropertyChanging("CategoryId");
                _CategoryId = StructuralObject.SetValidValue(value, "CategoryId");
                ReportPropertyChanged("CategoryId");
                OnCategoryIdChanged();
            }
        }
        private global::System.Int32 _CategoryId;
        partial void OnCategoryIdChanging(global::System.Int32 value);
        partial void OnCategoryIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false, "Title");
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Subject
        {
            get
            {
                return _Subject;
            }
            set
            {
                OnSubjectChanging(value);
                ReportPropertyChanging("Subject");
                _Subject = StructuralObject.SetValidValue(value, false, "Subject");
                ReportPropertyChanged("Subject");
                OnSubjectChanged();
            }
        }
        private global::System.String _Subject;
        partial void OnSubjectChanging(global::System.String value);
        partial void OnSubjectChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Body
        {
            get
            {
                return _Body;
            }
            set
            {
                OnBodyChanging(value);
                ReportPropertyChanging("Body");
                _Body = StructuralObject.SetValidValue(value, false, "Body");
                ReportPropertyChanged("Body");
                OnBodyChanged();
            }
        }
        private global::System.String _Body;
        partial void OnBodyChanging(global::System.String value);
        partial void OnBodyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AdminId
        {
            get
            {
                return _AdminId;
            }
            set
            {
                OnAdminIdChanging(value);
                ReportPropertyChanging("AdminId");
                _AdminId = StructuralObject.SetValidValue(value, "AdminId");
                ReportPropertyChanged("AdminId");
                OnAdminIdChanged();
            }
        }
        private global::System.Int32 _AdminId;
        partial void OnAdminIdChanging(global::System.Int32 value);
        partial void OnAdminIdChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbSIMailerModel", "FK_tblMails_tblMailCategory", "tblMailCategory")]
        public tblMailCategory tblMailCategory
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblMailCategory>("dbSIMailerModel.FK_tblMails_tblMailCategory", "tblMailCategory").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblMailCategory>("dbSIMailerModel.FK_tblMails_tblMailCategory", "tblMailCategory").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblMailCategory> tblMailCategoryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblMailCategory>("dbSIMailerModel.FK_tblMails_tblMailCategory", "tblMailCategory");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblMailCategory>("dbSIMailerModel.FK_tblMails_tblMailCategory", "tblMailCategory", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbSIMailerModel", "FK_tblSendTo_tblMails", "tblSendTo")]
        public EntityCollection<tblSendTo> tblSendToes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblSendTo>("dbSIMailerModel.FK_tblSendTo_tblMails", "tblSendTo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblSendTo>("dbSIMailerModel.FK_tblSendTo_tblMails", "tblSendTo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbSIMailerModel", Name="tblMailCategory")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblMailCategory : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblMailCategory object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="category">Initial value of the Category property.</param>
        public static tblMailCategory CreatetblMailCategory(global::System.Int32 id, global::System.String category)
        {
            tblMailCategory tblMailCategory = new tblMailCategory();
            tblMailCategory.Id = id;
            tblMailCategory.Category = category;
            return tblMailCategory;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Category
        {
            get
            {
                return _Category;
            }
            set
            {
                OnCategoryChanging(value);
                ReportPropertyChanging("Category");
                _Category = StructuralObject.SetValidValue(value, false, "Category");
                ReportPropertyChanged("Category");
                OnCategoryChanged();
            }
        }
        private global::System.String _Category;
        partial void OnCategoryChanging(global::System.String value);
        partial void OnCategoryChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbSIMailerModel", "FK_tblMails_tblMailCategory", "tblMail")]
        public EntityCollection<tblMail> tblMails
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblMail>("dbSIMailerModel.FK_tblMails_tblMailCategory", "tblMail");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblMail>("dbSIMailerModel.FK_tblMails_tblMailCategory", "tblMail", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbSIMailerModel", Name="tblPerson")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblPerson : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblPerson object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="emailId">Initial value of the EmailId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="typeId">Initial value of the TypeId property.</param>
        public static tblPerson CreatetblPerson(global::System.Int32 id, global::System.String emailId, global::System.String name, global::System.Int32 typeId)
        {
            tblPerson tblPerson = new tblPerson();
            tblPerson.Id = id;
            tblPerson.EmailId = emailId;
            tblPerson.Name = name;
            tblPerson.TypeId = typeId;
            return tblPerson;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EmailId
        {
            get
            {
                return _EmailId;
            }
            set
            {
                OnEmailIdChanging(value);
                ReportPropertyChanging("EmailId");
                _EmailId = StructuralObject.SetValidValue(value, false, "EmailId");
                ReportPropertyChanged("EmailId");
                OnEmailIdChanged();
            }
        }
        private global::System.String _EmailId;
        partial void OnEmailIdChanging(global::System.String value);
        partial void OnEmailIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TypeId
        {
            get
            {
                return _TypeId;
            }
            set
            {
                OnTypeIdChanging(value);
                ReportPropertyChanging("TypeId");
                _TypeId = StructuralObject.SetValidValue(value, "TypeId");
                ReportPropertyChanged("TypeId");
                OnTypeIdChanged();
            }
        }
        private global::System.Int32 _TypeId;
        partial void OnTypeIdChanging(global::System.Int32 value);
        partial void OnTypeIdChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbSIMailerModel", "FK_tblPerson_tblPersonType", "tblPersonType")]
        public tblPersonType tblPersonType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblPersonType>("dbSIMailerModel.FK_tblPerson_tblPersonType", "tblPersonType").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblPersonType>("dbSIMailerModel.FK_tblPerson_tblPersonType", "tblPersonType").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblPersonType> tblPersonTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblPersonType>("dbSIMailerModel.FK_tblPerson_tblPersonType", "tblPersonType");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblPersonType>("dbSIMailerModel.FK_tblPerson_tblPersonType", "tblPersonType", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbSIMailerModel", "FK_tblSendTo_tblPerson", "tblSendTo")]
        public EntityCollection<tblSendTo> tblSendToes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblSendTo>("dbSIMailerModel.FK_tblSendTo_tblPerson", "tblSendTo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblSendTo>("dbSIMailerModel.FK_tblSendTo_tblPerson", "tblSendTo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbSIMailerModel", Name="tblPersonType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblPersonType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblPersonType object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static tblPersonType CreatetblPersonType(global::System.Int32 id, global::System.String name)
        {
            tblPersonType tblPersonType = new tblPersonType();
            tblPersonType.Id = id;
            tblPersonType.Name = name;
            return tblPersonType;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbSIMailerModel", "FK_tblPerson_tblPersonType", "tblPerson")]
        public EntityCollection<tblPerson> tblPersons
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblPerson>("dbSIMailerModel.FK_tblPerson_tblPersonType", "tblPerson");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblPerson>("dbSIMailerModel.FK_tblPerson_tblPersonType", "tblPerson", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbSIMailerModel", Name="tblSendTo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblSendTo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblSendTo object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="mailId">Initial value of the MailId property.</param>
        /// <param name="personId">Initial value of the PersonId property.</param>
        /// <param name="adminId">Initial value of the AdminId property.</param>
        public static tblSendTo CreatetblSendTo(global::System.Int32 id, global::System.Int32 mailId, global::System.Int32 personId, global::System.Int32 adminId)
        {
            tblSendTo tblSendTo = new tblSendTo();
            tblSendTo.Id = id;
            tblSendTo.MailId = mailId;
            tblSendTo.PersonId = personId;
            tblSendTo.AdminId = adminId;
            return tblSendTo;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MailId
        {
            get
            {
                return _MailId;
            }
            set
            {
                OnMailIdChanging(value);
                ReportPropertyChanging("MailId");
                _MailId = StructuralObject.SetValidValue(value, "MailId");
                ReportPropertyChanged("MailId");
                OnMailIdChanged();
            }
        }
        private global::System.Int32 _MailId;
        partial void OnMailIdChanging(global::System.Int32 value);
        partial void OnMailIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PersonId
        {
            get
            {
                return _PersonId;
            }
            set
            {
                OnPersonIdChanging(value);
                ReportPropertyChanging("PersonId");
                _PersonId = StructuralObject.SetValidValue(value, "PersonId");
                ReportPropertyChanged("PersonId");
                OnPersonIdChanged();
            }
        }
        private global::System.Int32 _PersonId;
        partial void OnPersonIdChanging(global::System.Int32 value);
        partial void OnPersonIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AdminId
        {
            get
            {
                return _AdminId;
            }
            set
            {
                OnAdminIdChanging(value);
                ReportPropertyChanging("AdminId");
                _AdminId = StructuralObject.SetValidValue(value, "AdminId");
                ReportPropertyChanged("AdminId");
                OnAdminIdChanged();
            }
        }
        private global::System.Int32 _AdminId;
        partial void OnAdminIdChanging(global::System.Int32 value);
        partial void OnAdminIdChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbSIMailerModel", "FK_tblSendTo_tblMails", "tblMail")]
        public tblMail tblMail
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblMail>("dbSIMailerModel.FK_tblSendTo_tblMails", "tblMail").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblMail>("dbSIMailerModel.FK_tblSendTo_tblMails", "tblMail").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblMail> tblMailReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblMail>("dbSIMailerModel.FK_tblSendTo_tblMails", "tblMail");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblMail>("dbSIMailerModel.FK_tblSendTo_tblMails", "tblMail", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbSIMailerModel", "FK_tblSendTo_tblPerson", "tblPerson")]
        public tblPerson tblPerson
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblPerson>("dbSIMailerModel.FK_tblSendTo_tblPerson", "tblPerson").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblPerson>("dbSIMailerModel.FK_tblSendTo_tblPerson", "tblPerson").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblPerson> tblPersonReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblPerson>("dbSIMailerModel.FK_tblSendTo_tblPerson", "tblPerson");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblPerson>("dbSIMailerModel.FK_tblSendTo_tblPerson", "tblPerson", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
